CR#1
noincomedev/newsweek-clone pull request #1
Opened 2019-04-23 14:06 UTC by noincomedev

2019-04-23 15:00 UTC, mcrd25 requested changes
# First of all! Great so far! Just a couple more changes till 🚀 😄 

## please address following 
- Please address review comments
- Media query break points are a bit off, the max width of the main content is a bit small (compare actual website to newsweek.com
here is an instance of wonky break point used by y'all
![Screen Shot 2019-04-23 at 10 49 23 AM](https://user-images.githubusercontent.com/31193823/56590793-a7c98a80-65b5-11e9-89b4-7b765dac0ae3.png)
![Screen Shot 2019-04-23 at 10 49 32 AM](https://user-images.githubusercontent.com/31193823/56590799-aa2be480-65b5-11e9-9a4a-74d9d95f3d2c.png)
Both same screen sizes but different layout. Same goes for rest of website.
-  Would not harp too much on nav, but some work is needed at smaller media queries, please see original website to compare changes.

- You guys just need to look at bootstrap docs see which one media breakpoints are what width so that you can use right classes, changes should be easy to implement

- Please work on latest news section for smaller screens, it's a bit messy, in fact, many sections do, but this one looks the most untidy in small screens along with nav.

** I really want this already awesome looking website to look better on your portfolio, please address changes 👍 **

** You guys have a great README 👍 **

** You guys have to get the bootstrap column classes right, do you need help? **

### Any questions at all please message me on slack @maya or comment here. If my comments confuse you please come to me and clarify 👍. Project is almost 💯. Submit another code review please 😄 . Good job so far. Looks similar to newsweek.com on larger screens. Soon it will be 🥇

2019-04-23 15:00 UTC, mcrd25 commented on assets/styles.css
> +  font-size: 20px;
Remove this since you are using `font` in line 73. :)

2019-04-23 15:00 UTC, mcrd25 commented on assets/styles.css
> +  font-weight: 800;
Since you have both `font-weight` and `font-family` in line 60, you may use `font` shorthand as you have in line 73.

See this [link](https://www.w3schools.com/csSref/pr_font_font.asp) for more.

2019-04-23 15:00 UTC, mcrd25 commented on assets/styles.css
> +  line-height: 20px;
Remove this since you are using `font` in line 73. :)

2019-04-23 15:00 UTC, mcrd25 commented on assets/styles.css
> +  font-family: "Roboto Condensed", sans-serif;
Line 90 to 93 could all be in one line using `font` property instead.  I noticed you used it sometimes for line 77 for instance. Try to be consistent. It is best to use shorthand for this case though. 

You are free to disagree 👍

2019-04-23 15:00 UTC, mcrd25 commented on assets/styles.css
> +  font-family: Arial, Helvetica, sans-serif;
Why do you have this when you have defined the font in line 119?

2019-04-23 15:00 UTC, mcrd25 commented on assets/styles.css
> +  font: bold 16px/26px "roboto condensed", sans-serif;
Wondering why you did not set the font-family on whole body as Roboto Condensed by default? It's the main font you are using correct?

2019-04-23 15:00 UTC, mcrd25 commented on assets/styles.css
> +  font-size: 20px;
Same as previous mentions with `font` shorthand for lines 90 to 94. This is last time I will mention it, identify other occurrences and fix please 😃

2019-04-25 14:03 UTC, noincomedev commented on assets/styles.css
> +  font-size: 20px;
why do i have to remove this? is a class that im actually using.

2019-04-25 14:20 UTC, closed without merging